spring:
  config:
    import: aws-secretsmanager:mini-collaboration-board-db

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${port}/${database}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${jwt_secret}
    access-expiration: 36000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable : true

aws:
  ses:
    access-key: ${aws_ses_access_key}
    secret-key: ${aws_ses_secret_key}
    from: ${aws_ses_from}
  region: ${aws_region}

app:
  base-url: http://localhost:8080

logging:
  level:
    org.hibernate.SQL: error
    org.hibernate.orm.jdbc.bind: error

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false




