spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniBoard?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ***REMOVED*** # todo AWS 처리
    access-expiration: 36000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ***REMOVED***
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: ture
          timeout: 5000
          starttls.enable : true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

